@startuml Article

state Article {
  state "Created" as C
  state "Edited" as E 
  state "Deleted" as D
  state loggedIn <<choice>>

  [*] --> C

  C --> loggedIn : Login check
  loggedIn --> C : Not logged in
  
  loggedIn --> E
  loggedIn --> D
  
  E --> E
  E --> D
  
  D --> [*]
}

@enduml
