@startuml Article

state Article {
  state "Created" as C
  state "Edited" as E 
  state "Deleted" as D
  state loggedIn <<choice>>
  
  [*] --> loggedIn
  C --> loggedIn
  E --> loggedIn
  
  loggedIn --> C
  loggedIn --> D
  loggedIn --> E
  
  D --> loggedIn
  D --> [*]
}

@enduml
