@startuml
class Article {
  - title: String
  - text: String
  - author: User
  - lastEdit: Date
  - version: int
}

class Category {
  - name: String
}

class Contributor {
  - firstName: String
  - surname: String
  - birthDate: Date
  - university: University
}

class Permission {
  - name: String
}

class Role {
  - name: String
}

class University {
  - name: String
  - place: String
}

Permission "1..*" -- "1..*" Role
Contributor "1..*" -- "1..*" Role 
Contributor "1..*" -- "0..*" Article : edits
Contributor "1" -- "1" University


Article "1..*" -- "0..*" Category
@enduml
