@startuml domain

class Article {
  - title: String
  - text: String
  - lastEdit: Date
  - version: int
}

class Category {
  - name: String
}

class Contributor {
  - firstName: String
  - surname: String
  - birthDate: Date
  - university: University
}

class University {
  - name: String
  - place: String
}

Contributor "1..*" -- "0..*" Article : edits
Contributor "1..*" -- "1" University

Article "1..*" -- "2" Category

@enduml
