@startuml search

state Search {
  state "Results" as R
  state "NoResults" as NR
  
  [*] --> R : Search
  [*] --> NR : Search
  
  R -left-> R : Search
  R -left-> NR : Search
  
  NR --> NR : Search
  NR --> R : Search
  
  R --> [*]
  NR --> [*]
}

@enduml
