@startuml "state"

state SearchArticle {
  [*] --> SearchByCategory
  [*] --> SearchByUserInput
  
  SearchByUserInput --> ShowFoundResults
  SearchByCategory --> ShowFoundResults
  
  ShowFoundResults -left-> SearchByCategory 
  ShowFoundResults -left-> SearchByUserInput
  
  SearchByCategory --> ShowNoResultsFound
  SearchByUserInput --> ShowNoResultsFound
  
  ShowNoResultsFound -left-> SearchByCategory
  ShowNoResultsFound -left-> SearchByUserInput
  
  ShowFoundResults --> [*]
  ShowNoResultsFound --> [*]
}
  
@enduml
